# Generated by Django 6.0.2 on 2026-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_device_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
