# Generated by Django 6.0.2 on 2026-03-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_notification_add_data_if_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE accounts_notification "
                "ADD COLUMN IF NOT EXISTS read_at timestamptz NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

