# Generated by Django 6.0.2 on 2026-03-27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_notification_add_read_at_if_missing"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE accounts_user "
                        "ADD COLUMN IF NOT EXISTS profile_image varchar(100) NULL;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="user",
                    name="profile_image",
                    field=models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.user_profile_image_upload_to,
                    ),
                ),
            ],
        ),
    ]
