# Generated by Django 6.0.2 on 2026-02-27 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_riderequest_feedback_riderequest_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riderequest",
            name="is_paid",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="payout_status",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="riderequest",
            name="razorpay_payment_id",
        ),
    ]
