# Generated by Django 6.0.2 on 2026-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_remove_riderequest_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
