{{- if and .Values.notificationWorker.enabled (not .Values.notificationWorker.firebase.existingSecretName) .Values.secrets.firebaseServiceAccountJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "locomotion.firebaseSecretName" . }}
  labels:
    {{- include "locomotion.labels" . | nindent 4 }}
type: Opaque
stringData:
  firebase-service-account.json: |
{{ .Values.secrets.firebaseServiceAccountJson | indent 4 }}
{{- end }}
