{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "locomotion.secretName" . }}
  labels:
    {{- include "locomotion.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  EMAIL_HOST_USER: {{ .Values.secrets.emailHostUser | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.emailHostPassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.secrets.razorpayKeySecret | quote }}
{{- end }}
