{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locomotion.fullname" . }}-web
  labels:
    {{- include "locomotion.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "locomotion.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "locomotion.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "locomotion.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "locomotion.backendImage" . }}
          imagePullPolicy: {{ .Values.images.backend.pullPolicy }}
          command:
            {{- toYaml .Values.web.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.web.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ include "locomotion.configMapName" . }}
            - secretRef:
                name: {{ include "locomotion.secretName" . }}
          readinessProbe:
            httpGet:
              path: /swagger/
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /swagger/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
